### PR TITLE
Readme update: add imgs and descriptions for most important sections

### PR DESCRIPTION
**Pull request by Omarelsherif010**
There are still some sections to add. 
If you have time add a max of 3 images per section.

You will find all images inside imgs folder

### CODE REVIEW

**Review by amr-atif — APPROVED** [review]
great

**Comment by sarasweidan2023** [comment]
Good job

**Comment by ahmedtarek26** [comment]
You haven't added images for ADNI data and Data analysis sections in readme, right?

**Comment by Omarelsherif010** [comment]
> You haven't added images for ADNI data and Data analysis sections in readme, right?

Not yet.
If you have time, go ahead

**Pull request merged**
